# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Blog on Github
email: nickyfoto@gmail.com
description: "A personal blog build with Jekyll and github.io"
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "http://nickyfoto.github.io/Blog" # the base hostname & protocol for your site
twitter_username: miguelmac
github_username:  nickyfoto

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
permalink: /entries/:title
